name: CI

on:
  - push
  - pull_request

env:
  SKIP_PREFLIGHT_CHECK: 'true'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install server modules
      run: npm install
    - name: Install client modules
      working-directory: ./client
      run: npm install
    - name: Build server modules
      run: npm run build
    - name: Build client modules
      working-directory: ./client
      run: npm run build
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install server modules
      run: npm install
    - name: Install client modules
      working-directory: ./client
      run: npm install
    - name: Run server ESLint
      run: npm run lint
    - name: Run client ESLint
      working-directory: ./client
      run: npm run lint
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install server modules
      run: npm install
    - name: Install client modules
      working-directory: ./client
      run: npm install
    - name: Build client code
      run: npm run build
      working-directory: ./client
    - name: Run server tests
      run: npm run test
      env:
        YOUTUBE_KEY: ${{ secrets.YOUTUBE_KEY }}
